gripper_mask_1:
- id:                   finger_1
  initial_position:
    x:                  0.0
    y:                  -0.10
    z:                  0.0
  plate_normal:
    x:                  0.0
    y:                  1.0
    z:                  0.0
  trajectory_angle:     -0.087
  plate_height:         0.03
  plate_width:          0.03
  max_grasp_angle:      0.18
  pinch_group:          -1
- id:                   finger_2
  initial_position:
    x:                  -0.05
    y:                  0.1
    z:                  0.0
  plate_normal:
    x:                  0.0
    y:                  -1.0
    z:                  0.0
  trajectory_angle:     -3.054
  plate_height:         0.03
  plate_width:          0.03
  max_grasp_angle:      0.18
  pinch_group:          0
- id:                   finger_3
  initial_position:
    x:                  0.05
    y:                  0.1
    z:                  0.0
  plate_normal:
    x:                  0.0
    y:                  -1.0
    z:                  0.0
  trajectory_angle:     -3.054
  plate_height:         0.03
  plate_width:          0.03
  max_grasp_angle:      0.18
  pinch_group:          0
